// <auto-generated />
using System;
using AlirezaEShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlirezaEShop.Migrations
{
    [DbContext(typeof(AlirezaEShopContext))]
    partial class AlirezaEShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlirezaEShop.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "ASP .NET Core",
                            Name = "ASP"
                        },
                        new
                        {
                            ID = 2,
                            Description = "ساعت مچی",
                            Name = "ساعت مچی"
                        },
                        new
                        {
                            ID = 3,
                            Description = "لباس ورزشی",
                            Name = "گروه لباس ورزشی"
                        },
                        new
                        {
                            ID = 4,
                            Description = "لوازم منزل",
                            Name = "لوازم منزل"
                        });
                });

            modelBuilder.Entity("AlirezaEShop.Models.CategoryToProduct", b =>
                {
                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "CategoryID");

                    b.HasIndex("CategoryID");

                    b.ToTable("CategoryToProducts");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 1,
                            CategoryID = 2
                        },
                        new
                        {
                            ProductID = 1,
                            CategoryID = 3
                        },
                        new
                        {
                            ProductID = 1,
                            CategoryID = 4
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 2
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 3
                        },
                        new
                        {
                            ProductID = 2,
                            CategoryID = 4
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 1
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 2
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 3
                        },
                        new
                        {
                            ProductID = 3,
                            CategoryID = 4
                        });
                });

            modelBuilder.Entity("AlirezaEShop.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("quantityInStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            price = 850.4m,
                            quantityInStock = 2
                        },
                        new
                        {
                            Id = 2,
                            price = 3302.0m,
                            quantityInStock = 5
                        },
                        new
                        {
                            Id = 3,
                            price = 2500m,
                            quantityInStock = 3
                        });
                });

            modelBuilder.Entity("AlirezaEShop.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("UserID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AlirezaEShop.Models.OrderDetails", b =>
                {
                    b.Property<int>("DeatilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeatilID"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.HasKey("DeatilID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("orderDetails");
                });

            modelBuilder.Entity("AlirezaEShop.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureExtention")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("itemID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("itemID")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "مبل خانگی",
                            Name = "مبل",
                            PictureExtention = ".jpg",
                            itemID = 1
                        },
                        new
                        {
                            ID = 2,
                            Description = "ساعت مچی",
                            Name = "ساعت",
                            PictureExtention = ".jpg",
                            itemID = 2
                        },
                        new
                        {
                            ID = 3,
                            Description = "یخچال ساید",
                            Name = "یخچال",
                            PictureExtention = ".jpg",
                            itemID = 3
                        });
                });

            modelBuilder.Entity("AlirezaEShop.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            Email = "Alireza@email.com",
                            IsAdmin = true,
                            Password = "12345",
                            RegisterDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AlirezaEShop.Models.CategoryToProduct", b =>
                {
                    b.HasOne("AlirezaEShop.Models.Category", "category")
                        .WithMany("CategoryToProduct")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlirezaEShop.Models.Product", "product")
                        .WithMany("CategoryToProduct")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("product");
                });

            modelBuilder.Entity("AlirezaEShop.Models.Order", b =>
                {
                    b.HasOne("AlirezaEShop.Models.User", "user")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("AlirezaEShop.Models.OrderDetails", b =>
                {
                    b.HasOne("AlirezaEShop.Models.Order", "order")
                        .WithMany("orderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlirezaEShop.Models.Product", "product")
                        .WithMany("orderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("AlirezaEShop.Models.Product", b =>
                {
                    b.HasOne("AlirezaEShop.Models.Item", "item")
                        .WithOne("product")
                        .HasForeignKey("AlirezaEShop.Models.Product", "itemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");
                });

            modelBuilder.Entity("AlirezaEShop.Models.Category", b =>
                {
                    b.Navigation("CategoryToProduct");
                });

            modelBuilder.Entity("AlirezaEShop.Models.Item", b =>
                {
                    b.Navigation("product")
                        .IsRequired();
                });

            modelBuilder.Entity("AlirezaEShop.Models.Order", b =>
                {
                    b.Navigation("orderDetails");
                });

            modelBuilder.Entity("AlirezaEShop.Models.Product", b =>
                {
                    b.Navigation("CategoryToProduct");

                    b.Navigation("orderDetails");
                });

            modelBuilder.Entity("AlirezaEShop.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
